# Generated by Django 4.2 on 2023-04-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
