# Generated by Django 4.2 on 2023-04-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_alter_cart_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
