# Generated by Django 4.2 on 2023-05-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0010_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(default='Processing', max_length=20)),
                ('shipping_address', models.CharField(default='', max_length=255)),
                ('billing_address', models.CharField(default='', max_length=255)),
                ('payment_method', models.CharField(default='', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('products', models.ManyToManyField(to='shopping.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
